// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi5_z0tCBtOyfxBn5_DYeJnXtD9smpl60',
    appId: '1:486561867543:web:3b9269a97550698607b952',
    messagingSenderId: '486561867543',
    projectId: 'zyra-moments-49be6',
    authDomain: 'zyra-moments-49be6.firebaseapp.com',
    storageBucket: 'zyra-moments-49be6.firebasestorage.app',
    measurementId: 'G-Q49GPSZDQ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_5Yjge88zzehbzFCXVUihqnJOb1Xv76Q',
    appId: '1:486561867543:android:7aab1b11c448cf3c07b952',
    messagingSenderId: '486561867543',
    projectId: 'zyra-moments-49be6',
    storageBucket: 'zyra-moments-49be6.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDi5_z0tCBtOyfxBn5_DYeJnXtD9smpl60',
    appId: '1:486561867543:web:665f047cc471888307b952',
    messagingSenderId: '486561867543',
    projectId: 'zyra-moments-49be6',
    authDomain: 'zyra-moments-49be6.firebaseapp.com',
    storageBucket: 'zyra-moments-49be6.firebasestorage.app',
    measurementId: 'G-961DVFET73',
  );
}
